# Generated by Django 4.2.5 on 2023-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signinapp", "0002_remove_contactform_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploaded_images/")),
            ],
        ),
    ]
